modLoader="javafml"
loaderVersion="[${javafml_version},)"
license="All Rights Reserved"

[[mods]]
modId="wutilities"
version="${version}"
displayName="wUtilities"
logoFile="icon.png"
authors="wSmoothie, literal.uu"
description='''Lets servers control which wWorldMap and wWaypoints client features are available.'''
displayTest="IGNORE_ALL_VERSION"

[[dependencies.wutilities]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="SERVER"

[[dependencies.wutilities]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="SERVER"
