modLoader="javafml"
loaderVersion="[${javafml_version},)"
license="All Rights Reserved"

[[mods]]
modId="wworldmap_utils"
version="${version}"
displayName="wWorldMap Utils"
logoFile="icon.png"
authors="wSmoothie, literal.uu"
description='''Lets servers control which wWorldMap client features are available.'''
displayTest="IGNORE_ALL_VERSION"

[[dependencies.wworldmap_utils]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="SERVER"

[[dependencies.wworldmap_utils]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="SERVER"
