modLoader="javafml"
loaderVersion="[3,)"
license="All Rights Reserved"

[[mods]]
modId="wutilities"
version="${version}"
displayName="wUtilities"
logoFile="icon.png"
authors="wSmoothie, literal.uu"
description='''Lets servers control which wWorldMap and wWaypoints client features are available.'''
displayTest="IGNORE_ALL_VERSION"

[[dependencies.wutilities]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="SERVER"

[[dependencies.wutilities]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="SERVER"
