name: wUtilities
version: '${version}'
main: com.wworldmap.utils.paper.WorldMapUtilsPlugin
description: Lets servers control which wWorldMap and wWaypoints client features are available.
authors: [wSmoothie, literal.uu]
api-version: '1.20'
folia-supported: true
